version: "3"

tasks:
  default:
    cmds:
      - task: build
      - task: run
  build:
    cmds:
      - zig build
  run:
    cmds:
      - ./zig-out/bin/zcrypto {{.CLI_ARGS}}
  vhs:
    cmds:
      - vhs ./vhs/zcrypto.tape
