name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [ x86-linux, x86_64-linux, aarch64-linux, riscv64-linux ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@default
      with:
        version: master

    - name: Build
      run: zig build -Doptimize=ReleaseSafe -Dtarget=${{ matrix.target }}

    - name: Archive executable
      uses: actions/upload-artifact@main
      with:
        name: zcrypto
        path: zig-out/bin/*